//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumir_ws.Ws_listado {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Ws_listado.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listado_control", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet listado_control();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listado_control", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> listado_controlAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listado_control_cedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet listado_control_cedula(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listado_control_cedula", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> listado_control_cedulaAsync(string cedula);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : consumir_ws.Ws_listado.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<consumir_ws.Ws_listado.WebService1Soap>, consumir_ws.Ws_listado.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet listado_control() {
            return base.Channel.listado_control();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> listado_controlAsync() {
            return base.Channel.listado_controlAsync();
        }
        
        public System.Data.DataSet listado_control_cedula(string cedula) {
            return base.Channel.listado_control_cedula(cedula);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> listado_control_cedulaAsync(string cedula) {
            return base.Channel.listado_control_cedulaAsync(cedula);
        }
    }
}
